mkdir -p api/src/functions api/src/shared api/test sql

git mv bootstrap.js api/src/functions/bootstrap.js
git mv employees.js api/src/functions/employees.js
git mv host.json api/src/functions/schedules.js
git mv constants.js api/src/shared/constants.js
git mv repository.js api/src/shared/repository.js
git mv schedules.js api/src/shared/validation.js
git mv validation.test.js api/test/validation.test.js
git mv local.settings.sample.json api/local.settings.sample.json

git rm schedule.js
git rm package.json
git rm validation.js
